//! Shared test fixtures and helpers (test-only; never compiled into the
//! library facade — the generated tests.zig imports it like any other
//! module).
//!
//! Contents:
//! - CPU-only `Scene`/`Mesh` fixtures for tests that exercise subsystems
//!   touching only the allocator (capture/restore, material loading, ...).
//!   These replace the per-file `testScene`/`testMesh` copies: the fields
//!   left `undefined` are GPU-backed objects the tested code never
//!   dereferences, and `std.mem.zeroes` cannot build them in Zig 0.16
//!   (non-nullable pointer fields).
//! - Comptime corpus mutators for the `std.testing.fuzz` smoke passes
//!   (see loader/obj_fuzz.zig and siblings): valid seed + truncations +
//!   byte flips + garbage, all derived at compile time.

const std = @import("std");
const Scene = @import("scene.zig").Scene;
const Mesh = @import("mesh.zig").Mesh;
const Texture = @import("texture.zig").Texture;
const CubeTexture = @import("texture.zig").CubeTexture;

/// Minimal CPU-only Scene for subsystem tests (serialization capture/restore,
/// material loading): only `.allocator` is dereferenced. The default textures
/// and render passes are GPU-backed and stay `undefined`.
pub fn testScene(alloc: std.mem.Allocator) Scene {
    return .{
        .allocator = alloc,
        .profiler = @import("profiler.zig").Profiler.init(alloc),
        .default_white_texture = std.mem.zeroes(Texture),
        .default_normal_texture = std.mem.zeroes(Texture),
        .default_cube_texture = std.mem.zeroes(CubeTexture),
        .lights = .{},
        .probes = .{},
        .shadows = .{ .pass = undefined },
        .sky = .{ .pass = undefined },
        .postfx = .{
            .postprocess_pass = undefined,
            .ssao_pass = undefined,
            .bloom_pass = undefined,
            .glow_pass = undefined,
            .outline_pass = undefined,
        },
        .forward = .{},
        .particles = .{ .pass = undefined },
    };
}

/// Buffer-free Mesh for tests that only touch name/transform/visibility/
/// material fields (serialization): sokol buffers stay empty.
pub fn testMesh(name: []const u8) Mesh {
    return .{
        .name = name,
        .vertex_buffer = .{},
        .index_buffer = .{},
        .index_count = 0,
    };
}

/// Engine vector constructor, re-exported so test files can build Vec3 values
/// without importing the math module themselves.
pub const vec3 = @import("math").Vec3.new;

// ---------------------------------------------------------------------------
// Comptime fuzz corpus builders: each turns a valid seed into the standard
// malformed family (truncate at a power-of-two-ish spread + single-byte flips
// at structural offsets + garbage with a valid magic prefix). Entries are
// comptime-known, so the whole corpus is a plain array literal.
// ---------------------------------------------------------------------------

/// A corpus entry: comptime bytes with a stable name for failure reports.
pub const Corpus = []const []const u8;

/// `seed` truncated at each of `offsets` (clamped to seed length).
pub fn truncations(comptime s: []const u8, comptime offsets: []const usize) Corpus {
    comptime var out: [offsets.len][]const u8 = undefined;
    inline for (offsets, 0..) |raw_off, i| {
        out[i] = s[0..@min(raw_off, s.len)];
    }
    const frozen = out;
    return &frozen;
}

/// `seed` with one byte XORed at each of `offsets` (clamped; empty seed wins).
pub fn flips(comptime s: []const u8, comptime offsets: []const usize) Corpus {
    comptime var out: [offsets.len][]const u8 = undefined;
    inline for (offsets, 0..) |raw_off, i| {
        if (s.len == 0) {
            out[i] = "";
        } else {
            const off: usize = @min(raw_off, s.len - 1);
            out[i] = s[0..off] ++ &[_]u8{s[off] ^ 0xff} ++ s[off + 1 ..];
        }
    }
    const frozen = out;
    return &frozen;
}

/// `magic ++ garbage`: header-valid garbage, the class most likely to slip
/// past early validation and reach the payload decoder.
pub fn magicGarbage(comptime magic: []const u8, comptime garbage: []const u8) Corpus {
    const entry = magic ++ garbage;
    return &[_][]const u8{entry};
}

/// Concatenates corpus groups into one.
pub fn join(a: Corpus, b: Corpus) Corpus {
    comptime var out: [a.len + b.len][]const u8 = undefined;
    inline for (a, 0..) |entry, i| out[i] = entry;
    inline for (b, 0..) |entry, i| out[a.len + i] = entry;
    const frozen = out;
    return &frozen;
}

/// Resolves the bytes one fuzz iteration should parse. In the corpus smoke
/// pass (`zig build test`) the corpus entry is handed back verbatim, so seeds
/// stay readable, human-meaningful files. Under the fuzz runner
/// (`zig build test --fuzz`, smith.in == null) the smith-generated bytes of
/// this iteration are produced into `generated_buf`.
pub fn fuzzInput(smith: *std.testing.Smith, generated_buf: []u8) []const u8 {
    if (smith.in) |raw| return raw;
    const n = smith.slice(generated_buf);
    return generated_buf[0..n];
}
